sudo: required
services:
  - docker
  
before_install:
  - docker build -t sandeepksd/loginwen-travis .

#language: java
#jdk: openjdk8

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Loginwen"
  env: "Loginwen-env"
  bucket_name: "elasticbeanstalk-us-east-2-344916721838"
  bucket_path: "Loginwen"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"